stages:
  - build
  - test
default:
  tags:
    - cpu

BuildCode:
  stage: build

  before_script:
    - apt-get update
    - apt-get install -y cmake git
    - mkdir 3rdparty && cd 3rdparty
    - git clone https://github.com/google/googletest.git
    - export GOOGLE_TEST_DIR=googletest

  script:
    - cd ../
    - mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Release .. && make

  artifacts:
    untracked: false
    when: on_success
    expire_in: 7 days
    paths:
      - "bin/"
TestCode:
  stage: test
